pipeline:
  test:
    image: ruby:2.4
    commands:
      - bundle install --path=gems --retry=5 --jobs=5
      - bundle exec rubocop
      - bundle exec rspec
      - gem build drone-chef.gemspec

#   docker:
#     storage_driver: overlay
#     repo: plugins/drone-chef
#     tags: [ "latest" ]
#     when:
#       branch: master
#       event: push
#
# plugin:
#   name: Chef
#   desc: Publish files and artifacts to Chef Server
#   type: publish
#   image: plugins/drone-chef
#   labels:
#     - chef
#     - ruby
