AllCops:
  Exclude:
    - gems/**/*
    - test/chef_cookbook/**/*
    - drone-chef.gemspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
